rumbl/lib/rumbl_web/router.ex
defmodule RumblWeb.Router do
  use RumblWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug RumblWeb.Auth # now we can use that information downstream
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", RumblWeb do
    pipe_through :browser

    resources "/users", UserController, only: [:index, :show, :new, :create]
    # Resources shorthand form for defining CRUD operations
    # only: allows us to define resources we want defined

    # :index, and :show not rando. These are part of the :show, :index, :new, :create, :edit, :update and :delete actions all frequetly used in Phoenix.
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    get "/", PageController, :index
    get "/watch/:id", WatchController, :show 
  end

  scope "/manage", RumblWeb do
    pipe_through [:browser, :authenticate_user] #This forces that we authenticate before creating/loading resource

    resources "/videos", VideoController
  end

  # Other scopes may use custom stacks.
  # scope "/api", RumblWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: RumblWeb.Telemetry
    end
  end
end

rumbl/lib/rumbl/multimedia/video.ex
defmodule Rumbl.Multimedia.Video do
  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, Rumbl.Multimedia.Permalink, authgenerate: true} #WE are defining primary key, protocol for casting and indicating that database autogenerates it for us.
  schema "videos" do
    field :description, :string
    field :title, :string
    field :url, :string
    field :slug, :string

    belongs_to :category, Rumbl.Multimedia.Category 
    belongs_to :user, Rumbl.Accounts.User #Creates association between User and video
    # this is called a foreign key.

    #Can roll forward and back. This allows for reverting updates.

    #WE WANT TO MAKE SURE DEPENDEICES ARE ONE WAY

    has_many :annotations, Rumbl.Multimedia.Annotation #We are saying that we have many annotations for each video
  

    timestamps()
  end

  @doc false
  def changeset(video, attrs) do
    video
    |> cast(attrs, [:url, :title, :description, :category_id]) #Whitelist what may be allowed in
    #user_id is not castable or required because comes from internal data(the application). The application is responsible for associating the right user to each video.
    |> validate_required([:url, :title, :description])
    |> assoc_constraint(:category) #Makes sure that category follows it's constaint of only having a name that matches category.
    #If user updates or middle of udating and categories change, want to deliver nice message to user indicating why the error occured. 
    #Failing to throw an error leads to database INCONSISTENCIES. that is bad. Let us not do that
    #Swallowing the error leads to  bad UX. Let us NOT do that either.
    |> slugify_title()
  end

  defp slugify_title(changeset) do
    case fetch_change(changeset, :title) do
        {:ok, new_title} -> put_change(changeset, :slug, slugify(new_title))
        :error -> changeset
    end
  end

  defp slugify(str) do #changesets allow us specify how to change for each type of data in each possible senerio!

  #Changesets VALIDATE DATA BUT NOT DATA INTEGRITY. THAT is left to the database as constraints
    str
    |> String.downcase()
    |> String.replace(~r/[^\w-]+/u, "-")
  end
end

rumbl/lib/rumbl_web/controllers/video_controller.ex
defmodule RumblWeb.VideoController do
  use RumblWeb, :controller

  alias Rumbl.Multimedia
  alias Rumbl.Multimedia.Video

  def index(conn, _params, current_user) do
    videos = Multimedia.list_user_videos(current_user)
    render(conn, "index.html", videos: videos)
  end

  def new(conn, _params, __current_user) do
    changeset = Multimedia.change_video(%Video{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"video" => video_params}, current_user) do #Oh, this is beautiful, I'm able to define how all functions are treated within the controller so I don't have to replicate the same extraction code in 6 different places.

    case Multimedia.create_video(current_user, video_params) do
      {:ok, video} ->
        conn
        |> put_flash(:info, "Video created successfully.")
        |> redirect(to: Routes.video_path(conn, :show, video))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id},current_user) do
    IO.puts(Kernel.inspect conn)
    video = Multimedia.get_user_video!(current_user,id)
    render(conn, "show.html", video: video)
  end

  def edit(conn, %{"id" => id}, current_user) do
    video = Multimedia.get_user_video!(current_user, id)
    changeset = Multimedia.change_video(video)
    render(conn, "edit.html", video: video, changeset: changeset)
  end

  def update(conn, %{"id" => id, "video" => video_params},current_user) do
    video = Multimedia.get_user_video!(current_user, id)

    case Multimedia.update_video(video, video_params) do
      {:ok, video} ->
        conn
        |> put_flash(:info, "Video updated successfully.")
        |> redirect(to: Routes.video_path(conn, :show, video))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", video: video, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}, current_user) do
    video = Multimedia.get_user_video!(current_user, id)
    {:ok, _video} = Multimedia.delete_video(video)
#We have made our application secure WITHOUT sacrifiying readability or usability. How awesome is that.
    conn
    |> put_flash(:info, "Video deleted successfully.")
    |> redirect(to: Routes.video_path(conn, :index))
  end

  def action(conn, _) do # We are redefining the action parameter in controller. 
  # We are passing in the connection AND we are exposing the paramters and  current_user as values that are scoped in all controller actions.
  #this is better because we are setting up the values that is called with garunteed options


  #this is called before any actual action explicity.
    args = [conn, conn.params, conn.assigns.current_user]
    apply(__MODULE__, action_name(conn), args)
  end

  plug :load_categories when action in [:new, :create, :edit, :update] #load this pipe for the pipeline when one of the follwoing actions
  
  defp load_categories(conn, _) do
    assign(conn, :categories, Multimedia.list_alphabetical_categories()) #Add to the connection the list of categories so that future functions can just access it
  end
end

rumbl/lib/rumbl_web/views/video_view.ex
defmodule RumblWeb.VideoView do
  use RumblWeb, :view #We know that it will render each like index, edit,delete new as functions

  def category_select_options(categories) do
    for category <- categories, do: {category.name, category.id}
  end
end

rumbl/lib/rumbl_web/templates/video/edit.html.eex
<h1>Edit Video</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.video_path(@conn, :update, @video)) %>

<span><%= link "Back", to: Routes.video_path(@conn, :index) %></span>

rumbl/lib/rumbl_web/templates/video/form.html.eex
<%= form_for @changeset, @action, fn f -> %> <!-- Automatically changes form name to match action (CRUD)-->
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :url %>
  <%= text_input f, :url %>
  <%= error_tag f, :url %>

  <%= label f, :title %>
  <%= text_input f, :title %>
  <%= error_tag f, :title %>

  <%= label f, :description %>
  <%= textarea f, :description %>
  <%= error_tag f, :description %>

  <%= label f, :category_id, "Category" %>
  <%= select f, :category_id, category_select_options(@categories), prompt: "Choose a category" %> <!-- Accessing the function that is defined in video_view.ex-->

  <!-- @categories is passsed from video_controlller via the assign statement-->

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

rumbl/lib/rumbl_web/templates/video/index.html.eex
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th></th>
      <th></th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for video <- @videos do %>
    <tr>
      <td><%= video.title %></td>

      <td>
        <span><%= link "Watch", to: Routes.watch_path(@conn, :show, video), class: "button" %></span>
        <span><%= link "Edit", to: Routes.video_path(@conn, :edit, video) %></span>
        <span><%= link "Delete", to: Routes.video_path(@conn, :delete, video), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

rumbl/lib/rumbl_web/templates/video/new.html.eex
<h1>New Video</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.video_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.video_path(@conn, :index) %></span>

rumbl/lib/rumbl_web/templates/video/show.html.eex
<h1>Show Video</h1>

<ul>

  <li>
    <strong>Url:</strong>
    <%= @video.url %>
  </li>

  <li>
    <strong>Title:</strong>
    <%= @video.title %>
  </li>

  <li>
    <strong>Description:</strong>
    <%= @video.description %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.video_path(@conn, :edit, @video) %></span>
<span><%= link "Back", to: Routes.video_path(@conn, :index) %></span>