rumbl/lib/rumbl_web/router.ex
defmodule RumblWeb.Router do
  use RumblWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug RumblWeb.Auth # now we can use that information downstream
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", RumblWeb do
    pipe_through :browser

    resources "/users", UserController, only: [:index, :show, :new, :create]
    # Resources shorthand form for defining CRUD operations
    # only: allows us to define resources we want defined

    # :index, and :show not rando. These are part of the :show, :index, :new, :create, :edit, :update and :delete actions all frequetly used in Phoenix.
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    get "/", PageController, :index
    get "/watch/:id", WatchController, :show 
  end

  scope "/manage", RumblWeb do
    pipe_through [:browser, :authenticate_user] #This forces that we authenticate before creating/loading resource

    resources "/videos", VideoController
  end

  # Other scopes may use custom stacks.
  # scope "/api", RumblWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: RumblWeb.Telemetry
    end
  end
end

rumbl/lib/rumbl_web/views/layout_view.ex
defmodule RumblWeb.LayoutView do
  use RumblWeb, :view
end

rumbl/lib/rumbl_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Rumbl · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script>window.userToken = "<%= assigns[:user_token]%>"</script> <!-- We are injecting user token into webpage so that we can pick it up by script-->
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <section class="container">
      <nav role='navigation'>
        <ul>
          <!-- When  the user is avalibe show top part, otherwise show login part -- >

          <!-- -->
          <%= if @current_user do %>
            <li><%= @current_user.username %></li>
            <li><%= link "My Videos", to: Routes.video_path(@conn, :index)%></li>
            <li>
              <%= link "Log out", to: Routes.session_path(@conn, :delete, @current_user), method: "delete"%> <!-- Need to pass method, otherwise defaults to get which is NOT what we want here. Questions is whjere is session_path  and user_path coming from-->
            </li>
          <% else %>
          <!-- I sEE what is happening! I'm calling a specific route and mode and the system is filling in the link logistics. This is so beautiful. -->

          <!-- I have defined both a user_path and a session_path in router, and :new and :delete are methods that I have defined for those routes. This is seriously beautiful.-->
            <li><%= link "Register", to: Routes.user_path(@conn, :new)%></li>
            <li><%= link "Log in", to: Routes.session_path(@conn, :new)%> </li>
          <% end %>
        </ul>
      </nav>
    </section>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
  </body>
</html>